version: '3'
name: laravel-project

services:

    # PHP
    php:
        container_name: php
        platform: linux/x86_64
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    # Nginx
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 90:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    # DATABASE (MySQL)
    db:
        container_name: mysql
        image: mysql:8.1
        restart: always
        ports:
            - 3307:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: ducphap0112
